version: "3.3"
services:
  mongo:
    image: mongo:4.2.3
    container_name: mongo-4.2.3
    restart: "no"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: guest
    volumes:
      - ./data-mongo:/data/db # mongo data mounting point
      - ./sql:/root/sql # sql for export/import

  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    restart: "no"
    environment:
      - PGADMIN_DEFAULT_EMAIL=guest@local.com
      - PGADMIN_DEFAULT_PASSWORD=guest
    ports:
      - 2345:80
